name: Publish JAR

on:
  push:
    tags:
      - 'v*'

jobs:
  run-tests:
    uses: ./.github/workflows/test.yml

  publish:
    needs: run-tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11
          cache: gradle
      - name: Set version from Git tag
        id: set_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
      - name: Build and publish
        run: ./gradlew publish
        env:
          TOKEN: ${{ secrets.TOKEN }}
          USERNAME: abcqwq
